Input command should not be auto-corrected (#777)
tchapgouv/tchap-ios pull request #798
Opened 2023-03-29 16:05 UTC by NicolasBuquet

Fix #777 

Linked to Element issue https://github.com/vector-im/element-ios/issues/7424

2023-03-30 15:30 UTC, odelcroi commented
it seems it should be pushed to element

2023-04-03 07:45 UTC, NicolasBuquet commented
@odelcroi Pushed to Element : https://github.com/vector-im/element-ios/pull/7462

2023-04-03 07:49 UTC, odelcroi requested changes

2023-04-03 07:49 UTC, odelcroi commented on Riot/Modules/Room/Views/InputToolbar/RoomInputToolbarView.swift
> +        // Triggers auto-correct if needed and if it is not a command.
I would add a comment that this modification should be removed when the Element PR is merged and mainlined to Tchap https://github.com/vector-im/element-ios/pull/7462

2023-04-03 08:14 UTC, aulamber approved these changes

2023-04-03 08:19 UTC, merged