843 xsss amelioration ux wording et organisation des settings securite
tchapgouv/tchap-ios pull request #845
Opened 2023-06-08 17:30 UTC by NicolasBuquet

Fix #843 

![Simulator Screen Shot - iPhone 14 - 2023-06-08 at 19 27 43](https://github.com/tchapgouv/tchap-ios/assets/18608158/c6378fa1-9ce9-40e1-ad35-7b952c0a06cf)
![Simulator Screen Shot - iPhone 14 - 2023-06-08 at 19 28 24](https://github.com/tchapgouv/tchap-ios/assets/18608158/2dd24938-fdf1-45e8-bc04-c5f61a89768c)

2023-06-09 07:38 UTC, odelcroi requested changes

2023-06-09 07:38 UTC, odelcroi commented on Riot/Assets/en.lproj/Vector.strings
> +"device_verification_self_verify_open_on_other_device_title" = "Vérify this device"; // Tchap
ya un "é"

2023-06-09 07:38 UTC, odelcroi commented on Riot/Assets/fr.lproj/Vector.strings
> +"secrets_recovery_with_key_recover_action" = "Utilizer le Code de Récupération"; // Tchap
Utiliser

2023-06-09 07:38 UTC, odelcroi commented on Riot/Assets/fr.lproj/Vector.strings
>  "secrets_recovery_with_key_recovery_key_placeholder" = "Saisir la clé de récupération";
code ?

2023-06-12 13:17 UTC, NicolasBuquet commented on Riot/Assets/en.lproj/Vector.strings
> +"device_verification_self_verify_open_on_other_device_title" = "Vérify this device"; // Tchap
Fixed

2023-06-12 13:17 UTC, NicolasBuquet commented on Riot/Assets/fr.lproj/Vector.strings
> +"secrets_recovery_with_key_recover_action" = "Utilizer le Code de Récupération"; // Tchap
Fixed

2023-06-12 13:20 UTC, merged