Activer les sondages (Polls) (#880)
tchapgouv/tchap-ios pull request #881
Opened 2023-09-22 17:24 UTC by NicolasBuquet

Fix #880 

![Simulator Screen Shot - iPhone 14 - 2023-09-22 at 19 20 43](https://github.com/tchapgouv/tchap-ios/assets/18608158/2824b397-4637-4843-8d39-0ee77b3b9853)

2023-09-26 09:39 UTC, yostyle commented on Riot/Modules/Room/RoomCoordinator.swift
>          // Tchap: Feature unavailable
You should remove this comment ?

2023-09-26 09:43 UTC, NicolasBuquet commented on Riot/Modules/Room/RoomCoordinator.swift
>          // Tchap: Feature unavailable
Done

2023-10-10 14:45 UTC, yostyle requested changes
La couleur du check devrait être le bleu de Tchap
<img width="403" alt="image" src="https://github.com/tchapgouv/tchap-ios/assets/1191674/191d7715-3810-4da7-b0d6-3fd528bd0d5b">

2023-10-10 16:17 UTC, NicolasBuquet commented
Done.

<img width="421" alt="Screenshot 2023-10-10 at 18 13 56" src="https://github.com/tchapgouv/tchap-ios/assets/18608158/8140ecf7-b345-4c16-ba6d-4fd25fc958b8">

2023-10-11 17:39 UTC, merged