Setup feature activation by instance for Tchap
tchapgouv/tchap-ios pull request #949
Opened 2024-01-04 11:26 UTC by NicolasBuquet

Fix #948

2024-01-04 12:11 UTC, yostyle requested changes

2024-01-04 12:11 UTC, yostyle commented on Tchap/Extensions/Account+Tchap.swift
la gestion des features ne devrait pas dépendre de Account. Dans une classe d'utilitaire si il y'en a une ou dans `BuildSetting` ?

2024-01-04 15:43 UTC, NicolasBuquet commented on Tchap/Extensions/Account+Tchap.swift
Les features sont basées sur le homeServer qui est stocké dans les credentials de l'Account.

Je pense que c'est le bon endroit.

2024-01-08 10:02 UTC, NicolasBuquet commented on Tchap/Extensions/Account+Tchap.swift
> +        return targetedFeature.contains(BuildSettings.tchapFeatureAnyInstance) || targetedFeature.contains(self.identityServerURL.replacingOccurrences(of: BuildSettings.serverUrlPrefix, with: ""))
done

2024-01-08 13:57 UTC, yostyle approved these changes
LGTM

2024-01-08 14:00 UTC, merged